name: cge_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  syncfusion_flutter_charts: ^21.2.6
  datetime_picker_formfield: ^2.0.0
  mask_text_input_formatter: ^2.4.0
  awesome_snackbar_content: ^0.1.2
  floating_action_bubble: ^1.1.4
  animated_splash_screen: ^1.1.0
  curved_navigation_bar: ^1.0.3
  font_awesome_flutter: ^10.3.0
  multi_select_flutter: ^4.0.0
  transparent_image: ^2.0.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  bluetooth_print: ^4.3.0
  mobile_scanner: ^3.4.1
  fluttertoast: ^8.2.1
  get_storage: ^2.0.3
  qr_flutter: ^4.1.0
  ionicons: ^0.2.2
  lottie: ^1.2.1
  http: ^0.13.5
  faker: ^2.1.0
  intl: ^0.18.0
  get: ^4.6.3
  cached_network_image: ^3.3.0
  flutter_gif: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/

  fonts:
     - family: Prompt-ExtraBoldItalic
       fonts:
         - asset: assets/fonts/Prompt-ExtraBoldItalic.ttf
     - family: 'Roboto-BoldItalic'
       fonts:
         - asset: 'assets/fonts/Roboto-BoldItalic.ttf'
     - family: 'Icones_Personalizado'
       fonts:
         - asset: 'assets/fonts/Icones_Personalizado.ttf'
